* Shakespeare Mode
  A major mode that provides syntax highlighting an indentation for
  editing Shakespearean templates (hamlet, lucius, julius).


** Installation
   The package currently isn't in any repository, but the install in painless.
   
   Clone this repo and add the directory to your emacs load path by adding the following
   line to your .emacs:

   #+BEGIN_SRC elisp
       (add-to-list 'load-path "/path/to/this/clone/")
   #+END_SRC

   and /after/ that line, load shakespeare-mode by adding this line:

   #+BEGIN_SRC elisp
       (load "shakespeare-mode")
   #+END_SRC

   And that's it. Open up a hamlet, lucius, or julius file to make sure it worked.


** Usage
   After installation, you'll have three new commands:

   #+BEGIN_SRC elisp
       shakespeare-hamlet-mode
       shakespeare-julius-mode
       shakespeare-lucius-mode
   #+END_SRC

   These are major modes. If you loaded shakespeare-mode correctly, then
   =.hamlet=, =.lucius=, and =.julius= should inherit their mode automatically.

   If for any reason they are not loading on the correct file types, you can of
   course try loading them explicity by running =M-x shakespeare-hamlet-mode= in
   the appropriate buffer OR you can always try adding the following line to
   your .emacs (change to the correct file type):

   #+BEGIN_SRC elisp
       (add-to-list 'auto-mode-alist  '("\\.lucius\\'" . shakespeare-lucius-mode))
   #+END_SRC


** Features
   Currently, shakespeare-mode supports basic syntax highlighting and indentation
   for hamlet, lucius, and julius files.

*** Variable Interpolation
     All of the modes support syntax highlighting for variable interpolation:

    #+BEGIN_SRC elisp
        #{...}
        @{...}
        ^{...}
    #+END_SRC

    ...etc, are highlighted inline.

*** Hamlet Mode
    shakespeare-hamlet-mode has pretty full support for hamlet features (let me know
    if any are missing!):

    - control flow statements (=$if=, =$forall=, =$maybe=, etc)
    - shorthand class and id attributes (=<p .some-class #some-id>=)
    - optional quotes around attribute values
    - no need to explicitly tag =div= elements.

*** Lucius Mode
    shakespeare-lucius-mode supports a lot of the same things has shakespeare-hamlet-mode

    - url and variable interpolation
    - nested css blocks
    - variable declaration
    - lucius mixins

*** Julius Mode
    Julius mode is the most basic of the modes, but supports Javascript syntax
    highlighting (derived from javascript-mode), indentation and the three forms
    of variable interpolation mentioned above.


** Todo (in order of priority)
    - Put package in ELPA or similar repository
    - Support for setting option attributes with colons, as dicussed [[http://www.yesodweb.com/book/shakespearean-templates#shakespearean-templates_attributes][here]].
    - Add syntax support for hamlet pagination
    - Support far Cassius (shakespeare-cassius-mode)


** Thanks
   [[purcell's less-css-mode]]
   I was originally using less-css-mode for editing lucius files, so I used parts of this
   mode's modified syntax-table to compose lucius'.

   [[https://github.com/lightquake/hamlet-mode][lightquake's hamlet mode]]
   I was able to use parts of the regexp's from this repo for syntax highlighting,
   and parts of the syntax-table. There's been some reformatting and minor restructure
   but this was a big help.
